# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Views Microservice - CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

    
jobs:
  views-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    defaults:
      run:
        working-directory: views
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Node dependencies
      run: npm install
    
    - name: Check Mocha 
      run: npm install mocha -g

    - name: Build 
      run: npm run transpile

    - name: Tests
      run: mocha dist/tests/index.spec.js
